/**
 * Veo Video Generation Flow
 * Integrates with Google Veo 3.1 for AI video generation
 */

import { getStorageService } from '@/lib/local-storage-service';

export interface GenerateVideoInput {
  prompt: string;
  userId: string;
  duration?: number;
}

export interface GenerateVideoOutput {
  videoUrl: string;
  model: string;
  answer: string;
}

/**
 * Generate video using Veo 3.1
 */
export async function generateVideoVeo(
  input: GenerateVideoInput
): Promise<GenerateVideoOutput> {
  const { prompt, userId, duration } = input;

  try {
    console.log('[Veo Flow] Generating video:', prompt);

    // Try Veo 3.1 Fast first
    let videoBlob: Blob;
    let model: string;

    try {
      videoBlob = await generateWithVeo(prompt, 'veo-3.1-fast-generate-preview', duration);
      model = 'veo-3.1-fast-generate-preview';
    } catch (error) {
      console.warn('[Veo Flow] Fast generation failed, trying regular...');
      videoBlob = await generateWithVeo(prompt, 'veo-3.1-generate-preview', duration);
      model = 'veo-3.1-generate-preview';
    }

    // Save to Local Storage
    const buffer = Buffer.from(await videoBlob.arrayBuffer());
    const storageService = getStorageService();
    
    const result = await storageService.uploadFile(buffer, {
      userId,
      type: 'generated-video',
      autoDelete: false,
    });

    const answer = `🎬 **Video Generated Successfully!**

**Your Prompt:** ${prompt}

**Generated by:** Google ${model}
**Duration:** ${duration || 'auto'} seconds

[View Video](${result.url})

The video is stored securely on the server and ready to view or download.`;

    return {
      videoUrl: result.url,
      model,
      answer,
    };
  } catch (error) {
    console.error('[Veo Flow] Video generation failed:', error);
    
    return {
      videoUrl: '',
      model: 'error',
      answer: `❌ **Video Generation Failed**

I encountered an error while generating your video: ${error instanceof Error ? error.message : 'Unknown error'}

Note: Video generation requires Google API access and may not be available in all regions. Please check your API configuration.`,
    };
  }
}

async function generateWithVeo(prompt: string, model: string, duration?: number): Promise<Blob> {
  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${process.env.GOOGLE_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: `Generate a video: ${prompt}` }]
        }],
        generationConfig: {
          responseModalities: ['VIDEO'],
          ...(duration && { videoDuration: duration }),
        }
      }),
    }
  );

  if (!response.ok) {
    throw new Error(`Veo API error: ${response.statusText}`);
  }

  const data = await response.json();
  
  const videoPart = data.candidates?.[0]?.content?.parts?.find(
    (p: any) => p.inlineData && p.inlineData.mimeType.startsWith('video/')
  );

  if (!videoPart) {
    throw new Error('No video generated');
  }

  const bytes = Uint8Array.from(
    atob(videoPart.inlineData.data),
    c => c.charCodeAt(0)
  );
  
  return new Blob([bytes], { type: videoPart.inlineData.mimeType });
}
