/**
 * SOHAM Image Generation Flow
 * Integrates with the SOHAM pipeline for AI image generation
 */

import { getSOHAMPipeline } from '@/lib/soham-image-pipeline';

export interface GenerateImageInput {
  prompt: string;
  userId: string;
  style?: 'realistic' | 'artistic' | 'anime' | 'sketch';
}

export interface GenerateImageOutput {
  imageUrl: string;
  enhancedPrompt: string;
  provider: string;
  model: string;
  answer: string;
}

/**
 * Generate image using SOHAM pipeline
 */
export async function generateImageSOHAM(
  input: GenerateImageInput
): Promise<GenerateImageOutput> {
  const { prompt, userId, style } = input;

  try {
    console.log('[SOHAM Flow] Generating image:', prompt);

    // Use SOHAM pipeline
    const pipeline = getSOHAMPipeline();
    const result = await pipeline.generate({
      userPrompt: prompt,
      userId,
      style,
    });

    // Format response with proper image display
    const answer = `🎨 **Image Generated Successfully!**

**Your Prompt:** ${prompt}

**Enhanced Prompt:** ${result.enhancedPrompt}

**Generated by:** ${result.provider}/${result.model}  
**Generation Time:** ${(result.generationTime / 1000).toFixed(2)}s

![Generated Image](${result.url})

[📥 Download Image](${result.url})

The image is stored securely and ready to use.`;

    return {
      imageUrl: result.url,
      enhancedPrompt: result.enhancedPrompt,
      provider: result.provider,
      model: result.model,
      answer,
    };
  } catch (error) {
    console.error('[SOHAM Flow] Image generation failed:', error);
    
    return {
      imageUrl: '',
      enhancedPrompt: prompt,
      provider: 'error',
      model: 'error',
      answer: `❌ **Image Generation Failed**

I encountered an error while generating your image: ${error instanceof Error ? error.message : 'Unknown error'}

Please try again with a different prompt or check if the API keys are configured correctly.`,
    };
  }
}
